### ISSUE TITLE
What is ZBar0?

### ISSUE THREAD

**Issue by robotpilot** [ROBOTIS-OP/robotis_op_rock_paper_scissors#1]
I saw the error related the 'ZBar0' when build the robotis_op_rock_paper_scissors package.
So, I installed the ros-indigo-zbar-ros, but don't solve the this problem.
I don't know what to do to solve the problem.

**Comment by kdaun** [comment]
It's the zBar library, used for qrcode detection.
You can install it as follows:
`sudo apt-get install libzbar0`
Anyway, this package is still under development.

**Comment by robotpilot** [comment]
Thanks for your comments. I will try to install the libzbar0. Thanks a lot, Kevin!
